#!/usr/bin/php
<?php
use Maude\Registry as Registry;
        
require_once("utility.php");

boot_strap();

try {
   // Get medwatch dbase settings from medwatch.ini
   $db_settings = Registry::registry('database');

   $pdo = new \PDO("mysql:host=localhost;dbname=" . $db_settings['dbname'],
                         $db_settings['dbuser'],
                         $db_settings['dbpasswd']);  
   
   $pdo->setAttribute( \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION );  
   
   $insert_count = 0;
  
   // Find new mdr_report_keys that are in table medwatch_report_20XX but are not in medwatch_report. To get these, do left outer join looking for "IF NULL".
   
   $select_query = "SELECT m2014.mdr_report_key, m2014.text_report, m2014.date_received, m2014.report_source_code
                    FROM medwatch_report_2014 as m2014 
                         LEFT OUTER JOIN
                         medwatch_report as m
                               ON m2014.mdr_report_key=m.mdr_report_key
                         WHERE m.mdr_report_key IS NULL ORDER BY m2014.mdr_report_key ASC";
   
    // SQL statement with named placeholders 
   $insert_medwatch_report_stmt = $pdo->prepare("INSERT INTO medwatch_report(mdr_report_key, text_report, date_received, report_source_code) values
                                (:mdr_report_key, :text_report, :date_received, :report_source_code )");

   // bind the parameters in each statement
   $insert_medwatch_report_stmt->bindParam(':mdr_report_key', $mdr_report_key, \PDO::PARAM_INT);
        
   $insert_medwatch_report_stmt->bindParam(':text_report', $text_report, \PDO::PARAM_STR);

   $insert_medwatch_report_stmt->bindParam(':date_received', $date_received, \PDO::PARAM_STR);

   $insert_medwatch_report_stmt->bindParam(':report_source_code', $report_source_code, \PDO::PARAM_STR);
   
   $insert_count = 0;

   foreach ($pdo->query($select_query) as $row) {

       $mdr_report_key = $row['mdr_report_key'];

       $text_report =  $row['text_report'];

       $date_received =  $row['date_received'];

       $report_source_code =  $row['report_source_code'];

       $insert_medwatch_report_stmt->execute();
       ++$insert_count;
   }
  
   echo "Total new records added to medwatch_report: $insert_count\n";  
   
} catch (Exception $e) {

   $errors = "\nException Thrown in " . $e->getFile() . " at line " . $e->getLine() . "\n";
      
   $errors .= "Stack Trace as string:\n" . $e->getTraceAsString() . "\n";
          
   $errors .= "Error message is: " .   $e->getMessage() . "\n";
      
   echo $errors;

} // end try
